# Generated by Django 5.1.1 on 2025-05-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('test_permission', 'test')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
