# Generated by Django 6.0 on 2026-06-23 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0024_remove_cupom_user'),
        ('authentication', '0010_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.cupom'),
        ),
    ]
