# Generated by Django 6.0 on 2026-06-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0024_remove_cupom_user'),
        ('authentication', '0011_user_cupom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cupom',
        ),
        migrations.AddField(
            model_name='user',
            name='cupom',
            field=models.ManyToManyField(blank=True, to='app_ecommerce.cupom'),
        ),
    ]
