# Generated by Django 5.1.1 on 2025-05-21 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='imagens/')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('intem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.itens')),
            ],
        ),
    ]
