# Generated by Django 5.1.1 on 2025-05-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='intem',
            new_name='item',
        ),
        migrations.AddField(
            model_name='empresa',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='itens',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
