# Generated by Django 5.1.1 on 2025-05-22 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0002_rename_intem_empresa_item_empresa_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='image',
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imagens/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_ecommerce.itens')),
            ],
        ),
    ]
