# Generated by Django 5.1.1 on 2025-05-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0003_remove_itens_image_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
