# Generated by Django 5.1.1 on 2025-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0004_itens_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='code',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='id',
        ),
        migrations.AddField(
            model_name='itens',
            name='code_item',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itens',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='itens_images/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
