# Generated by Django 5.2.1 on 2025-06-11 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0006_company_delete_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='item',
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='categorys',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='id_company',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code_item', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='itens_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
    ]
