# Generated by Django 5.2.1 on 2025-07-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0008_rename_image_item_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletronicdetails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shoesdetails',
            name='category',
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secundary_description', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_ecommerce.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.item')),
            ],
        ),
        migrations.DeleteModel(
            name='ClothingDetails',
        ),
        migrations.DeleteModel(
            name='EletronicDetails',
        ),
        migrations.DeleteModel(
            name='ShoesDetails',
        ),
    ]
