# Generated by Django 5.2.1 on 2025-07-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0009_remove_eletronicdetails_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='secundary_description',
        ),
    ]
