# Generated by Django 5.2.1 on 2025-07-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0010_remove_itemdetails_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
