# Generated by Django 5.2.1 on 2025-07-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0011_alter_itemdetails_color_alter_itemdetails_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='main_image',
            new_name='image',
        ),
    ]
