# Generated by Django 5.2.1 on 2025-07-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0012_rename_main_image_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_ecommerce.color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_ecommerce.size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_ecommerce.storage'),
        ),
    ]
