# Generated by Django 6.0 on 2026-05-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0017_ongs_alter_company_logo_alter_image_item_causa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='valor_arrecadado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='causa',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
