# Generated by Django 6.0 on 2026-05-27 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0020_causa_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_desconto', models.CharField(choices=[('PERC', 'Porcentagem'), ('FIXO', 'Valor Fixo')], max_length=4)),
                ('validade', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade_maxima', models.IntegerField(default=1)),
                ('quantidade_usada', models.IntegerField(default=0)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
