# Generated by Django 6.0 on 2026-05-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0021_cupom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='quantidade_maxima',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='quantidade_usada',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='valor_minimo',
        ),
        migrations.AddField(
            model_name='cupom',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
