# Generated by Django 6.0 on 2026-06-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0022_remove_cupom_ativo_remove_cupom_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='description',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='causa',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
