# Generated by Django 6.0 on 2026-06-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0026_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongs',
            name='description',
            field=models.CharField(default='Sem descrição', max_length=1000),
        ),
        migrations.AddField(
            model_name='ongs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos_ongs/'),
        ),
    ]
