# Generated by Django 5.2.1 on 2025-07-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0013_color_size_storage_alter_itemdetails_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app_ecommerce.size'),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='storage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app_ecommerce.storage'),
        ),
    ]
