# Generated by Django 6.0 on 2026-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0018_causa_valor_arrecadado_alter_causa_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='porcentagem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
