# Generated by Django 6.0 on 2026-05-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0019_causa_porcentagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
