# Generated by Django 6.0 on 2026-06-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0023_alter_causa_description_alter_causa_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='user',
        ),
    ]
