# Generated by Django 5.1.1 on 2025-05-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
                'permissions': [('ver_vendas', 'Can ver vendas'), ('cancelar_vendas', 'Can cancelar vendas'), ('atualizar_preco', 'Can atualizar preco ')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
    ]
