# Generated by Django 5.2.1 on 2025-06-11 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0007_category_remove_company_item_remove_company_id_and_more'),
        ('authentication', '0004_gerente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.company'),
            preserve_default=False,
        ),
    ]
