# Generated by Django 5.2.1 on 2025-06-11 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0007_category_remove_company_item_remove_company_id_and_more'),
        ('authentication', '0006_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.company'),
        ),
    ]
